path = File.expand_path('..', __FILE__)
$:.unshift File.expand_path("#{path}/../jruby/1.8/gems/activesupport-3.0.5/lib")
$:.unshift File.expand_path("#{path}/../jruby/1.8/gems/builder-2.1.2/lib")
$:.unshift File.expand_path("#{path}/../jruby/1.8/gems/i18n-0.6.0/lib")
$:.unshift File.expand_path("#{path}/../jruby/1.8/gems/activemodel-3.0.5/lib")
$:.unshift File.expand_path("#{path}/../jruby/1.8/gems/arel-2.0.9/lib")
$:.unshift File.expand_path("#{path}/../jruby/1.8/gems/tzinfo-0.3.30/lib")
$:.unshift File.expand_path("#{path}/../jruby/1.8/gems/activerecord-3.0.5/lib")
$:.unshift File.expand_path("#{path}/../jruby/1.8/gems/activerecord-jdbc-adapter-1.1.1/lib")
$:.unshift File.expand_path("#{path}/../jruby/1.8/gems/json-1.6.1-java/lib")
$:.unshift File.expand_path("#{path}/../jruby/1.8/gems/mime-types-1.18/lib")
$:.unshift File.expand_path("#{path}/../jruby/1.8/gems/rack-1.2.1/lib")
$:.unshift File.expand_path("#{path}/../jruby/1.8/gems/rest-client-1.6.7/lib")
$:.unshift File.expand_path("#{path}/../jruby/1.8/gems/tilt-1.2.1/lib")
$:.unshift File.expand_path("#{path}/../jruby/1.8/gems/sinatra-1.1.2/lib")
